### ISSUE TITLE
Need more information please

### ISSUE THREAD

**Issue by vibnwis** [abhinand4858/Pintos#1]
Hi there,
PintOS sounds interesting. Do you have any  more information and teaching materials on how to use it, please?

**Comment by bx1n** [comment]
Hi!

I was experimenting with this once I was learning operating systems course in my university. But later on I moved to check xv6 which is also similar OS framework but had more documentation. You could read more about it here and also provides an overview on how this can used for learning and also teaching about OS - https://web.stanford.edu/class/cs140/projects/pintos/pintos_1.html

xv6 labs - https://pdos.csail.mit.edu/6.828/2020/labs/util.html
